# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

t_cpp <- function(mat) {
    .Call('_rPracticePkg_t_cpp', PACKAGE = 'rPracticePkg', mat)
}

prod_cpp <- function(mat1, mat2) {
    .Call('_rPracticePkg_prod_cpp', PACKAGE = 'rPracticePkg', mat1, mat2)
}

t_prod_cpp <- function(mat1, mat2) {
    .Call('_rPracticePkg_t_prod_cpp', PACKAGE = 'rPracticePkg', mat1, mat2)
}

